# dclint configuration
# See: https://github.com/zavoloklom/docker-compose-linter
#
# Severity levels: 0 = disabled, 1 = warning, 2 = error

rules:
  # Disable rules that don't apply to this dev environment

  # Random port assignment (127.0.0.1::containerPort) triggers false positives
  no-duplicate-exported-ports: 0

  # The expected order puts 'extends' last, but common practice is extends first
  service-keys-order: 0

  # Services are organized logically (main app first), not alphabetically
  services-alphabetical-order: 0

  # Random port format (127.0.0.1::port) is valid but flagged incorrectly
  require-quotes-in-ports: 0
