name: Composer Normalize

on:
  push:
    branches:
    - main
    paths:
    - composer.json
    - .github/workflows/composer-normalize.yml
  pull_request:
    branches:
    - main

jobs:
  composer-normalize:
    if: ${{ !github.event.repository.is_template }}
    strategy:
      matrix:
        php-version: ['8.5']
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@1.0.2
    with:
      name: Normalize composer.json (check)
      run: composer normalize --dry-run
      php-version: ${{ matrix.php-version }}
