name: Composer Validate

on:
  push:
    branches:
    - main
    paths:
    - composer.json
    - .github/workflows/composer-validate.yml
  pull_request:
    branches:
    - main

jobs:
  composer-validate:
    if: ${{ !github.event.repository.is_template }}
    strategy:
      matrix:
        php-version: ['8.5']
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@1.0.2
    with:
      name: Validate composer.json
      run: composer validate --strict
      install-deps: false
      php-version: ${{ matrix.php-version }}
