name: Composer Validate

on:
  push:
    branches:
    - main
    paths:
    - composer.json
    - .github/workflows/composer-validate.yml
  pull_request:
    branches:
    - main

jobs:
  composer-validate:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.5
    with:
      name: Validate composer.json
      run: composer validate --strict
      install-deps: false
