name: PHP Syntax Check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  php-syntax-check:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.2
    with:
      name: PHP Syntax Check
      run: composer php-lint
      install-deps: false
