name: PHP Syntax Check

on:
  push:
    branches:
    - main
    paths:
    - '**.php'
    - composer.json
    - .github/workflows/php-syntax-check.yml
  pull_request:
    branches:
    - main

jobs:
  php-syntax-check:
    if: ${{ !github.event.repository.is_template }}
    strategy:
      matrix:
        php-version: ['8.5']
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@1.0.2
    with:
      name: PHP Syntax Check
      run: composer php-lint
      install-deps: false
      php-version: ${{ matrix.php-version }}
