name: PHP CodeSniffer

on:
  push:
    branches:
    - main
    paths:
    - '**.php'
    - '.phpcs.xml*'
    - 'phpcs.xml*'
    - composer.json
    - composer.lock
    - .github/workflows/phpcs.yml
  pull_request:
    branches:
    - main

jobs:
  phpcs:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.5
    with:
      name: Run PHP CodeSniffer
      run: composer phpcs
