name: PHPStan

on:
  push:
    branches:
    - main
    paths:
    - '**.php'
    - phpstan.neon
    - phpstan.neon.dist
    - phpstan-baseline.neon
    - composer.json
    - composer.lock
    - .github/workflows/phpstan.yml
  pull_request:
    branches:
    - main

jobs:
  phpstan:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.4
    with:
      name: Run PHPStan
      run: composer phpstan
