name: PHPStan

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  phpstan:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.2
    with:
      name: Run PHPStan
      run: composer phpstan
