name: Rector

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  rector:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.2
    with:
      name: Run Rector (dry-run)
      run: composer rector
