name: Rector

on:
  push:
    branches:
    - main
    paths:
    - '**.php'
    - rector.php
    - composer.json
    - composer.lock
    - .github/workflows/rector.yml
  pull_request:
    branches:
    - main
    paths:
    - '**.php'
    - rector.php
    - composer.json
    - composer.lock
    - .github/workflows/rector.yml

jobs:
  rector:
    if: ${{ !github.event.repository.is_template }}
    uses: openCoreEMR/github-workflows-public/.github/workflows/php-composer-script.yml@0.0.4
    with:
      name: Run Rector (dry-run)
      run: composer rector
